config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users
  resources :orders
  resources :messages
  resources :products

  get "support/index", as: 'support'
  root 'index#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/message.rb
class Message < ApplicationRecord
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: [:show, :edit, :update, :destroy]

  # GET /messages
  # GET /messages.json
  def index
    @messages = Message.all
  end

  # GET /messages/1
  # GET /messages/1.json
  def show
  end

  # GET /messages/new
  def new
    @message = Message.new
  end

  # GET /messages/1/edit
  def edit
  end

  # POST /messages
  # POST /messages.json
  def create
    @message = Message.new(message_params)

    respond_to do |format|
      if @message.save
        format.html { redirect_to @message, notice: 'Message was successfully created.' }
        format.json { render :show, status: :created, location: @message }
      else
        format.html { render :new }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /messages/1
  # PATCH/PUT /messages/1.json
  def update
    respond_to do |format|
      if @message.update(message_params)
        format.html { redirect_to @message, notice: 'Message was successfully updated.' }
        format.json { render :show, status: :ok, location: @message }
      else
        format.html { render :edit }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1
  # DELETE /messages/1.json
  def destroy
    @message.destroy
    respond_to do |format|
      format.html { redirect_to messages_url, notice: 'Message was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_message
      @message = Message.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def message_params
      params.require(:message).permit(:name, :email, :subject, :message)
    end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/_form.html.erb
<fieldset>
    <legend>Send Us a Message</legend>
    <div class="row">
        <div class="col-md-8 col-sm-8">
            <%= form_for(message) do |f| %>
            <% if message.errors.any? %>
            <div id="error_explanation">
                <h2><%= pluralize(message.errors.count, "error") %>
                    prohibited this message from being saved:</h2>

                <ul>
                    <% message.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                    <% end %>
                </ul>
            </div>
            <% end %>
            <div class="field">
                <% if user_signed_in? %>
                <div class="col-md-2 col-sm-2 text-right">
                    <%= f.label :name %>
                </div>
                <div class="col-md-10 col-sm-10">
                    <%= f.text_field :name, value: "#{current_user.first_name} #{current_user.last_name}", placeholder: "John Doe" %>
                </div>
            <% else %>
                <div class="col-md-2 col-sm-2 text-right">
                    <%= f.label :name %>
                </div>
                <div class="col-md-10 col-sm-10">
                    <%= f.text_field :name, placeholder: "John Doe" %>
                </div>
                <% end %>
            </div>

            <div class="field">
                <% if user_signed_in? %>
                <div class="col-md-2 col-sm-2 text-right">
                    <%= f.label :email %>
                </div>
                <div class="col-md-10 col-sm-10">
                    <%= f.text_field :email, value: "#{current_user.email}", placeholder: "example@email.com" %>
                </div>
            <% else %>
                <div class="col-md-2 col-sm-2 text-right">
                    <%= f.label :email %>
                </div>
                <div class="col-md-10 col-sm-10">
                    <%= f.text_field :email, placeholder: "example@email.com" %>
                </div>
                <% end %>
            </div>

            <div class="field">
                <div class="col-md-2 col-sm-2 text-right">
                    <%= f.label :subject %>
                </div>
                <div class="col-md-10 col-sm-10">
                    <%= f.text_field :subject %>
                </div>
            </div>

            <div class="field">
                <div class="col-md-2 col-sm-2 text-right">
                    <%= f.label :message %>
                </div>
                <div class="col-md-10 col-sm-10">
                    <%= f.text_area :message, cols: "50", rows: "5" %>
                </div>
            </div>

            <div class="col-md-2 col-sm-2"></div>
            <div class="actions col-md-10 col-sm-10">
                <%= f.submit "Send", class: "btn btn-default" %>
            </div>
            <% end %>
        </div>
        <div class="col-md-4 col-sm-4">
            <address>
                <strong>Williams Specialty Company</strong><br>
                1234 Example Avenue, Suite 404<br>
                Citytown, OH 43000<br>
                <abbr title='Phone Number'>P:</abbr>
                (123) 456-7890
            </address>

            <address>
                <a href='mailto:#'>email.address@example.com</a>
            </address>
        </div>
    </div>
</fieldset><br><br>

app/views/messages/edit.html.erb
<h1>Editing Message</h1>

<%= render 'form', message: @message %>

<%= link_to 'Show', @message %> |
<%= link_to 'Back', messages_path %>

app/views/messages/index.html.erb
<h1>Messages</h1>

<table class="table">
  <thead class="thead-inverse">
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Subject</th>
      <th>Message</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @messages.each do |message| %>
      <tr>
        <td><%= message.name %></td>
        <td><%= message.email %></td>
        <td><%= message.subject %></td>
        <td><%= message.message %></td>
        <td><%= link_to 'Show', message %></td>
        <td><%= link_to 'Destroy', message, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/messages/new.html.erb
<%= render 'form', message: @message %>

<legend>Customer Testimonials</legend>
<div class="row">
    <div class="col-md-6 col-sm-6">
        <h5>
            <strong>D. Cerrone, Detroit MI</strong>
        </h5>
        <p class="text-justify">
            <em>"WSC is a lifesaver! My son’s baseball trophy was broken during our move to a new town and we knew he would be devastated when he saw it. My husband and I ordered him a new one from WSC and it was perfect"</em>
        </p>
        <h5>
            <strong>B.J. Penn, Seattle WA</strong>
        </h5>
        <p class="text-justify">
            <em>"My father’s 60 th birthday was last week, and about a month before that my wife and I ran into him at a local shopping center. He was looking for a new jacket but couldn’t find anything he liked so we got one for him from WSC with his military rank insignia on it and he loves it! The jacket is of high-quality and the embroidery is perfect."</em>
        </p>
        <h5>
            <strong>J. Jones, Salt Lake City UT</strong>
        </h5>
        <p class="text-justify">
            <em>"We bought our first house earlier this year and I wanted a ‘date established’ personalized plaque to hang near our doorbell. WSC has exactly what I was looking for and it only took a couple of minutes to create the design I had been picturing. Their prices are remarkably low compared to other businesses offering similar products."</em>
        </p>
    </div>
    <div class="col-md-6 col-sm-6">
        <h5>
            <strong>F. Mir, Galveston TX</strong>
        </h5>
        <p class="text-justify">
            <em>"I planned a trip for my family planned a trip to Disney World and wanted some matching t-shirts that really stood out. When we found WSC we couldn’t believe it – they have themes for just about everything and we found exactly what we were looking for! Thanks WSC."</em>
        </p>
        <h5>
            <strong>C. Weidman, Tipton NY</strong>
        </h5>
        <p class="text-justify">
            <em>"My boss wanted a plaque honoring all the employees that were still with him for the upcoming 20th anniversary of the opening of his business. After checking a few sites I found WSC and knew I had found the right place. The plaque and the engravings look amazing!"</em>
        </p>
        <h5>
            <strong>V. Belfort, Chicles ID</strong>
        </h5>
        <p class="text-justify">
            <em>"I am a [very] small business owner and I wanted to reward my employees with something different but useful as a thank you for their hard work last year. WSC’s selection made it easy. I found some very nice jackets and I was able put our company logo and their names on them and they look great!"</em>
        </p>
    </div>
    </div>
</div>
    <div class="text-center">
        <h5>
            <strong>A Gustafsson, Abilene TX</strong>
        </h5>
        <p>
            <em>Great price and looks great – 5 stars!!!</em>
        </p>
    </div>

app/views/messages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @message.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @message.email %>
</p>

<p>
  <strong>Subject:</strong>
  <%= @message.subject %>
</p>

<p>
  <strong>Message:</strong>
  <%= @message.message %>
</p>

<%= link_to 'Edit', edit_message_path(@message) %>