config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users
  resources :orders
  resources :messages
  resources :products

  get "support/index", as: 'support'
  root 'index#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<hr>
<div>
    <p id="footerController" class='text-center'>Developed by E. Okic, A. Ranga, J. Morelli, D. Harris, and P. King.
    <br>
    Copyright 2017©.
    </p>
    <br>
    <br>
    <br>
</div>

app/views/layouts/_navbar.html.erb
<nav class='navbar navbar-default' role='navigation'>
    <div class='container-fluid'>
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class='navbar-header'>
            <button type='button' class='navbar-toggle collapsed' data-toggle='collapse' data-target='#bs-docs-example-navbar-collapse-1'>
                <span class='sr-only'>Toggle navigation</span>
                <span class='icon-bar'></span>
                <span class='icon-bar'></span>
                <span class='icon-bar'></span>
            </button>
            <div class='navbar-brand'>
                <%= link_to 'WSC', root_path %>
            </div>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div id='bs-docs-example-navbar-collapse-1'>
            <ul class='nav navbar-nav'>
                <!-- Catalog -->
                <li><%= link_to 'Catalog', products_path %></li>
                <!-- Order -->
                <li><%= link_to 'Order', orders_path %></li>
                <!-- Contact Us -->
                <li><%= link_to 'Contact Us', new_message_path %></li>
                <!-- Customer Support -->
                <li><%= link_to 'Customer Support', support_path %></li>
            </ul>
            <ul class='nav navbar-nav navbar-right'>
                <% if user_signed_in? %>
                <% if current_user.admin? %>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownAdminMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Admin Controlls
                    </a>
                    <ul class="dropdown-menu">
                        <li><%= link_to "Customer Messages", messages_path %></li>
                        <li><%= link_to "Orders", orders_path %></li>
                        <li><%= link_to "Users", users_path %></li>
                    </ul>
                </li>
                <% end %>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownUserMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <%= current_user.email %>
                    </a>
                    <ul class="dropdown-menu">
                        <li><%= link_to "Edit Account", edit_user_registration_path, :method => :get %></li>
                        <li><%= link_to "Logout", destroy_user_session_path, :method => :delete %></li>
                    </ul>
                </li>
            <% else %>
                <li><%= link_to "Register", new_user_registration_path, :method => :get %></li>
                <li><%= link_to "Login", new_user_session_path, :method => :get %></li>
                <% end %>
            </ul>

        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Williams Specialty Company</title>

    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>

    <link type="text/css" rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <%= csrf_meta_tags %>
  </head>

  <body class="container">
      <%= render 'layouts/navbar' %>
        <% if notice %>
            <p class="alert alert-success"><%= notice %></p>
        <% end %>
        <% if alert %>
            <p class="alert alert-danger"><%= alert %></p>
        <% end %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>